# Jekyll theme
title: she qualifies
author: Sarah Ciston
email: sarahciston@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  how do you know you've made it until you've made something?
show_excerpts: true # set to true to show excerpts on the homepage
timezone: America/Los_Angeles

# url: https://shequalifies.glitch.me
# baseurl: https://shequalifies.glitch.me

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- pages/index.md
- pages/about.md

# Build settings
theme: just-the-docs #chalk minima #jekyll-theme-with-hack-css

#JUST THE DOCS####start

# Set a path/url to a logo that will be displayed instead of the title
# logo: "/assets/images/just-the-docs.png"

# Color scheme supports "light" (default) and "dark"
color_scheme: sarah #darkpurple

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

# Aux links for the upper right navigation
aux_links:
  "see the live source code":
    - "https://glitch.com/edit/#!/shequalifies"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true

# Sort order for navigation links
nav_sort: case_insensitive # default, equivalent to nil
# nav_sort: case_sensitive # Capital letters sorted before lowercase

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: false
back_to_top_text: "Back to top"

# Footer content
# appears at the bottom of every page's main content
footer_content: "&copy; 2020 Sarah Ciston." # "Distributed by an <a href=\"https://github.com/pmarsceill/just-the-docs/tree/master/LICENSE.txt\">MIT license.</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: false # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/sarahciston/shequalifies" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
# ga_tracking: UA-2709176-10
# ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false


#JUST THE DOCS####end

plugins:
 - jekyll-feed
 - jekyll-include-cache
 # - jekyll-seo-tag

# Build settings
livereload: true
encoding: utf-8
markdown: kramdown

kramdown:
  parse_block_html: true
  parse_span_html: true
  
exclude:
  - .sass-cache/
  - node_modules/
  - .gitignore
  - Gemfile
  - _config.yml
  - glitch.json
  - package.json
  - package-lock.json
  - watch.json
  - "*.save.*"
  
emptyArray: []

comments:
  receiver: https://shequalifies.glitch.me/newComment

defaults:
  -
    scope:
      path: ''
      type: pages
    values:
      layout: page
      author: sarahciston
      commenting: open
  -
    scope:
      path: 'posts'
      type: posts
    values:
      layout: post
      author: sarahciston
      commenting: open
  
